# name=input("please enter your name:")
# surname=input("please enter your surname:")
# age=input("please enter your age:")
# print(name+" "+surname+" "+str(age))

num1=int(input("please enter your num1:"))
num2=int(input("please enter your num2:"))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)