num1=int(input('please enter your num1:'))
num2=int(input('please enter your num1:'))
num3=int(input('please enter your num1:'))
num4=int(input('please enter your num1:'))
print(num1+num2+num3+num4)
print(num1-num2-num3-num4)
print(num1*num2*num3*num4)
print(num1/num2/num3/num4)